name: Build project
on:
    push:
        branches:
            - master
env:
    NODE_ENV: production
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v4
            - name: Installing extension dependencies
              working-directory: ./extension
              run: npm install --include dev
            - name: Installing backend dependencies
              working-directory: ./backend
              run: npm install
            - name: Building the extension
              working-directory: ./extension
              run: npm run build
            - name: Building the backend
              working-directory: ./backend
              run: npm run build
            - name: Deploy to output branch
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: output
                  FOLDER: ./build
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
